### ISSUE TITLE
Request: Kodi Leia support

### ISSUE THREAD

**Issue by krilok** [7adietri/script.radioparadise#5]
Any chance the script could be made compatible for Kodi Leia?

**Comment by 7adietri** [comment]
I'm not sure, to be honest. The addon code itself is probably not compatible with Leia's Python 2 runtime in its current state. And there also might be differences in the Kodi player that prevent it from working. When I started developing the addon, it had been [long announced](https://kodi.tv/article/attention-addon-developers-migration-python-3/) that Python 3 was the future, so I focused on that.

I would strongly recommend to update your Kodi installation, if possible, since Python 2 is already unmaintained, and eventually the Leia release will be as well.
